#!/usr/bin/env python3
"""View: spreadsheet. Generated from master.json — never hand-edited."""
import os
WORK = os.environ.get('WORK', '/home/claude')
OUT = os.environ.get('OUT', '/mnt/user-data/outputs')
import json
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

M = json.load(open(WORK+'/master.json'))
args = M['arguments']
OUT = OUT+'/argument-map.xlsx'

COLS = [
    ('ID', 'id', 8), ('Claim', 'claim', 46), ('Column', 'band_name', 20),
    ('Verdict', 'lands_verdict', 30), ('What it is', 'what', 20),
    ('Who does it', 'who', 20), ('Use', 'use', 12),
    ('Holds without Jesus\u2019 example', 'survives', 12),
    ('Key texts', 'texts', 28), ('The case (full)', 'case_full', 70),
    ('Strongest counter', 'counter_full', 55),
    ('Rejoinder', 'rejoinder_full', 55),
    ('Limits of this argument', 'risk', 45),
    ('Supports', '_sup', 55),
]

BANDFILL = {
    'Grammar and lexicon': 'E8F0E3', 'Precept': 'E3ECF5',
    'Confession and standards': 'F2ECDF', 'What Jesus did': 'F5E6E6',
    'Prudence': 'EFEAF3', 'Evidence and history': 'EEEEEE', None: 'F7F7F7',
}
thin = Side(style='thin', color='CCCCCC')

wb = Workbook()
ws = wb.active
ws.title = 'Arguments'

hdr = Font(bold=True, color='FFFFFF', size=10)
hf = PatternFill('solid', fgColor='3C4A5A')
for i, (name, _, w) in enumerate(COLS, 1):
    c = ws.cell(1, i, name)
    c.font, c.fill = hdr, hf
    c.alignment = Alignment(vertical='center', wrap_text=True)
    ws.column_dimensions[get_column_letter(i)].width = w
ws.row_dimensions[1].height = 34

for r, a in enumerate(args, 2):
    fill = PatternFill('solid', fgColor=BANDFILL.get(a.get('band_name'), 'F7F7F7'))
    for i, (_, key, _) in enumerate(COLS, 1):
        if key == '_sup':
            v = '\n'.join('\u2022 ' + s for s in (a.get('supports') or []))
        else:
            v = a.get(key)
        if isinstance(v, bool):
            v = 'Yes' if v else 'No'
        c = ws.cell(r, i, v if v is not None else '')
        c.alignment = Alignment(vertical='top', wrap_text=True)
        c.border = Border(left=thin, right=thin, top=thin, bottom=thin)
        c.font = Font(size=9, bold=(i == 1))
        if i <= 8:
            c.fill = fill
    ws.row_dimensions[r].height = 92

ws.freeze_panes = 'C2'
ws.auto_filter.ref = f'A1:{get_column_letter(len(COLS))}{len(args)+1}'

# --- second sheet: the two-axis grid -----------------------------------------
w2 = wb.create_sheet('Two axes')
whats = ['Word and sacrament received', 'Modeled, equipped, sent', 'Both', '\u2014']
whos = ['Officers', 'Every member, under officers', 'Both', '\u2014']
w2.cell(1, 1, 'what \u2193 / who \u2192').font = Font(bold=True)
for j, wh in enumerate(whos, 2):
    c = w2.cell(1, j, wh); c.font = Font(bold=True, size=9)
    c.alignment = Alignment(wrap_text=True, horizontal='center')
    w2.column_dimensions[get_column_letter(j)].width = 26
w2.column_dimensions['A'].width = 28
for i, wt in enumerate(whats, 2):
    c = w2.cell(i, 1, wt); c.font = Font(bold=True, size=9)
    c.alignment = Alignment(wrap_text=True)
    for j, wh in enumerate(whos, 2):
        ids = [a['id'] for a in args if a.get('what') == wt and a.get('who') == wh]
        cc = w2.cell(i, j, ', '.join(ids))
        cc.alignment = Alignment(wrap_text=True, vertical='top')
        cc.font = Font(size=9)
        cc.border = Border(left=thin, right=thin, top=thin, bottom=thin)
    w2.row_dimensions[i].height = 56

# --- third sheet: provenance --------------------------------------------------
w3 = wb.create_sheet('Provenance')
notes = [
    ['Source of truth', 'master.json'],
    ['Generated by', 'gen_xlsx.py'],
    ['Arguments', len(args)],
    ['', ''],
    ['Do not hand-edit this workbook.', 'Edit master.json and regenerate.'],
    ['Prose fields', 'Verbatim from argument-index.md, verified lossless.'],
    ['Structured fields', 'band / what / who / use / risk / texts.'],
    ['Blank Rejoinder', 'Means that entry has none in the source, not that it was dropped.'],
    ['Blank Column', 'Method arguments (A1\u2013A4) sit outside the board.'],
]
for i, (k, v) in enumerate(notes, 1):
    w3.cell(i, 1, k).font = Font(bold=True, size=9)
    w3.cell(i, 2, v).font = Font(size=9)
w3.column_dimensions['A'].width = 26
w3.column_dimensions['B'].width = 66

wb.save(OUT)
print(f'wrote {OUT}: {len(args)} rows, 3 sheets')
miss = [a['id'] for a in args if not a.get('rejoinder_full')]
print(f'rows with no rejoinder in source ({len(miss)}): {miss}')
